name: Staging Deploy (Lambda & Infra)

on:
  push:
    branches:
      - staging-env

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.9.4'
        terraform_wrapper: false
        
    - name: Apply latest terraform & lambda
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ADOBE_API_KEY: ${{ secrets.ADOBE_API_KEY }}
      run: |
        cd scripts
        ./deploy.sh stage-lambda-caching-service

